'use client';
import { useEffect, useMemo, useState } from 'react';

type Order={id:string;brand:string;source:string;customer:string;warehouse:string;status:string;total:number;created?:boolean};
type CartItem={sku:string;name:string;price:number;qty:number;stock:number};
const nav=['總覽','訂單中心','商品管理','庫存管理','採購管理','倉庫調撥','內部領用'];
const products=[{sku:'TRV-ORG-6PC',name:'旅行收納袋 6 件組',price:790,stock:48},{sku:'TRV-ADP-GR',name:'全球萬用轉接頭',price:1280,stock:5},{sku:'ANX-CB-02',name:'北歐抗菌砧板',price:680,stock:72},{sku:'CCI-VAC-M',name:'真空壓縮袋 M',price:199,stock:19}];
const initialOrders:Order[]=[{id:'#SP20260829021',brand:'TRAVO 玩一趟',source:'蝦皮',customer:'林怡君',warehouse:'桃園總倉',status:'庫存不足',total:1580},{id:'#AX8821',brand:'安鑫購物',source:'門市 POS',customer:'王家豪',warehouse:'台北門市倉',status:'待出庫',total:2360},{id:'#CC24082916',brand:'采采購物',source:'官網',customer:'張雅婷',warehouse:'台中倉',status:'揀貨中',total:680},{id:'#LN2026082911',brand:'TRAVO 玩一趟',source:'LINE',customer:'陳冠宇',warehouse:'桃園總倉',status:'待確認',total:2370}];
const genericRows:Record<string,string[][]>={
 '商品管理':products.map(p=>[p.sku,p.name,p.sku.startsWith('TRV')?'TRAVO 玩一趟':p.sku.startsWith('ANX')?'安鑫購物':'采采購物',String(p.stock),p.stock<10?'低庫存':'銷售中']),
 '庫存管理':[['TRV-ORG-6PC','旅行收納袋','桃園 48 · 台北 21 · 台中 15','安全庫存 20','可售 84'],['TRV-ADP-GR','萬用轉接頭','桃園 5 · 台北 8 · 台中 4','安全庫存 30','可售 17'],['ANX-CB-02','北歐抗菌砧板','桃園 72 · 台北 51 · 台中 19','安全庫存 25','可售 142']],
 '採購管理':[['PO-08291','豪盛生活用品','全球萬用轉接頭 · 50','桃園總倉','等待驗收'],['PO-08287','好旅國際','收納袋 · 120','桃園總倉','運送中'],['PO-08276','家適選物','砧板 · 80','台北門市倉','待到貨']],
 '倉庫調撥':[['TR-0829-03','折疊旅行袋 · 10','桃園總倉','台中倉','待確認'],['TR-0828-07','北歐抗菌砧板 · 15','桃園總倉','台北門市倉','運送中']],
 '內部領用':[['USE-0829-04','王小明','真空壓縮袋 · 商品拍攝','桃園總倉','待確認'],['USE-0828-11','李佳蓉','旅行收納袋 · 門市陳列','台北門市倉','已出庫']]
};

export default function Home(){
 const [active,setActive]=useState('總覽'); const [drawer,setDrawer]=useState(false); const [notice,setNotice]=useState('');
 const [orders,setOrders]=useState<Order[]>(initialOrders); const [brand,setBrand]=useState('TRAVO 玩一趟'); const [source,setSource]=useState('LINE 訂購');
 const [customer,setCustomer]=useState(''); const [phone,setPhone]=useState(''); const [delivery,setDelivery]=useState('宅配'); const [address,setAddress]=useState(''); const [warehouse,setWarehouse]=useState('桃園總倉'); const [payment,setPayment]=useState('未付款'); const [cart,setCart]=useState<CartItem[]>([]);
 useEffect(()=>{const saved=localStorage.getItem('flowstock-orders');if(saved)try{setOrders(JSON.parse(saved))}catch{}},[]);
 const show=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(''),2400)};
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0)+(delivery==='宅配'?80:0),[cart,delivery]);
 const addProduct=(sku:string)=>{const p=products.find(x=>x.sku===sku);if(!p)return;setCart(c=>{const found=c.find(x=>x.sku===sku);return found?c.map(x=>x.sku===sku?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]})};
 const createOrder=()=>{if(!customer||!phone||cart.length===0){show('請填寫客戶資料並至少加入一項商品');return}const shortage=cart.some(x=>x.qty>x.stock);const order:Order={id:`#MAN${Date.now().toString().slice(-8)}`,brand,source:`手動建立 · ${source}`,customer,warehouse,status:shortage?'庫存不足':'待出庫',total,created:true};const next=[order,...orders];setOrders(next);localStorage.setItem('flowstock-orders',JSON.stringify(next));setDrawer(false);setActive('訂單中心');setCustomer('');setPhone('');setAddress('');setCart([]);show(`訂單 ${order.id} 建立成功`)};
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">流</span><div><strong>FlowStock</strong><small>營運整合中心</small></div></div><div className="workspace"><span className="workspace-logo">群</span><div><small>目前工作區</small><b>群禾零售事業</b></div><span className="chev">⌄</span></div><nav><p className="nav-label">營運管理</p>{nav.map((item,i)=><button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}><span className="nav-icon">{['▦','▤','◇','▥','▣','⇄','↗'][i]}</span>{item}{item==='訂單中心'&&<em>{orders.filter(x=>x.status!=='已完成').length}</em>}</button>)}</nav><div className="sidebar-foot"><div className="avatar">陳</div><div><b>陳昱安</b><small>系統管理員</small></div><span>⋮</span></div></aside>
  <main><header><div><p className="breadcrumb">營運管理　/　<span>{active}</span></p><h1>{active==='總覽'?'早安，昱安':active}</h1><p className="subtitle">{active==='總覽'?'所有品牌、平台與倉庫，今天的重點一次掌握。':'集中管理所有品牌與通路資訊。'}</p></div><div className="header-actions"><div className="sync-state"><i/>外部訂單自動同步中<small>蝦皮・官網・LINE・門市 POS</small></div><button className="primary" onClick={()=>setDrawer(true)}>＋ 手動建立訂單</button></div></header>
   {active==='總覽'?<Dashboard orders={orders} setActive={setActive}/>:<Module active={active} orders={orders} show={show}/>} 
  </main>
  {drawer&&<><button className="backdrop" aria-label="關閉建立訂單" onClick={()=>setDrawer(false)}/><aside className="order-drawer"><div className="drawer-head"><div><small>特殊訂單／人工補單</small><h2>手動建立訂單</h2></div><button onClick={()=>setDrawer(false)} aria-label="關閉">×</button></div><div className="drawer-body">
   <section><h3><b>1</b> 訂單與客戶資料</h3><div className="form-grid"><label>所屬品牌<select value={brand} onChange={e=>setBrand(e.target.value)}><option>TRAVO 玩一趟</option><option>安鑫購物</option><option>采采購物</option></select></label><label>訂單來源<select value={source} onChange={e=>setSource(e.target.value)}><option>LINE 訂購</option><option>電話訂購</option><option>門市代客下單</option><option>團購／特殊訂單</option></select></label><label>客戶姓名<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="例如：王小明"/></label><label>手機號碼<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="0912-345-678"/></label></div></section>
   <section><h3><b>2</b> 商品與數量</h3><label className="product-picker">搜尋並加入商品<select defaultValue="" onChange={e=>{addProduct(e.target.value);e.target.value=''}}><option value="" disabled>選擇商品或 SKU</option>{products.map(p=><option key={p.sku} value={p.sku}>{p.sku} · {p.name}（桃園庫存 {p.stock}）</option>)}</select></label>{cart.length===0?<div className="empty-cart">尚未加入商品</div>:<div className="cart-list">{cart.map(item=><div className="cart-item" key={item.sku}><div><b>{item.name}</b><small>{item.sku} · 可用 {item.stock}</small></div><div className="qty"><button onClick={()=>setCart(c=>c.map(x=>x.sku===item.sku?{...x,qty:Math.max(1,x.qty-1)}:x))}>−</button><span>{item.qty}</span><button onClick={()=>setCart(c=>c.map(x=>x.sku===item.sku?{...x,qty:x.qty+1}:x))}>＋</button></div><strong>NT$ {(item.price*item.qty).toLocaleString()}</strong><button className="remove" onClick={()=>setCart(c=>c.filter(x=>x.sku!==item.sku))}>×</button></div>)}</div>}</section>
   <section><h3><b>3</b> 配送、倉庫與付款</h3><div className="form-grid"><label>配送方式<select value={delivery} onChange={e=>setDelivery(e.target.value)}><option>宅配</option><option>門市自取</option><option>超商取貨</option></select></label><label>出貨倉庫<select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option>桃園總倉</option><option>台北門市倉</option><option>台中倉</option></select></label><label className="wide">{delivery==='宅配'?'收件地址':'取貨說明'}<input value={address} onChange={e=>setAddress(e.target.value)} placeholder={delivery==='宅配'?'請輸入完整地址':'請輸入門市或備註'}/></label><label>付款狀態<select value={payment} onChange={e=>setPayment(e.target.value)}><option>未付款</option><option>已付款</option><option>貨到付款</option></select></label></div></section>
  </div><div className="drawer-foot"><div><span>訂單總額</span><strong>NT$ {total.toLocaleString()}</strong><small>{delivery==='宅配'?'含運費 NT$ 80':'免運費'} · {payment}</small></div><button className="secondary" onClick={()=>setDrawer(false)}>取消</button><button className="primary create" onClick={createOrder}>確認建立訂單</button></div></aside></>}
  {notice&&<div className="toast">✓　{notice}</div>}
 </div>
}

function Dashboard({orders,setActive}:{orders:Order[];setActive:(v:string)=>void}){const fresh=orders[0];return <><section className="metrics">{[['今日待處理',String(orders.filter(x=>x.status!=='已完成').length),'跨平台集中管理',''],['待出庫',String(orders.filter(x=>x.status==='待出庫').length),'最早 09:40',''],['待驗收入庫','3','共 126 件','amber'],['低庫存','7','2 項即將售罄','red'],['異常','2','需要立即處理','red']].map(([l,v,n,t])=><article key={l} className={`metric ${t}`}><div><span>{l}</span><i>→</i></div><strong>{v}</strong><small>{n}</small></article>)}</section><section className="process-card"><div><small>核心營運流程</small><h2>外部訂單進來後，系統自動接手後續作業</h2></div>{['平台訂單匯入','SKU 自動配對','檢查即時庫存','分配出貨倉庫','完成出庫'].map((x,i)=><span key={x}><b>{i+1}</b>{x}{i<4&&<i>→</i>}</span>)}</section><section className="top-grid"><article className="panel tasks"><div className="panel-head"><div><h2>今日待辦</h2><p>依優先順序排列需要處理的事項</p></div><button onClick={()=>setActive('訂單中心')}>查看全部 →</button></div>{orders.slice(0,4).map((o,i)=><button className="task-row clickable" key={o.id} onClick={()=>setActive('訂單中心')}><span className={`status-icon ${o.status==='庫存不足'?'urgent':'pending'}`}>{o.status==='庫存不足'?'!':'•'}</span><div><b>{o.source}訂單 {o.id}</b><small>{o.brand} · {o.customer}</small></div><span className={`tag ${o.status==='庫存不足'?'urgent':'pending'}`}>{o.status}</span><span className="row-arrow">›</span></button>)}</article><article className="panel orders"><div className="panel-head"><div><h2>今日訂單</h2><p>自動匯入與手動訂單統一計算</p></div></div><div className="order-total"><strong>{101+orders.filter(x=>x.created).length}</strong><span>筆訂單</span></div><div className="bar"><i className="b1"/><i className="b2"/><i className="b3"/></div><div className="brand-orders"><div><span className="dot d1"/>TRAVO 玩一趟 <b>32</b></div><div><span className="dot d2"/>安鑫購物 <b>48</b></div><div><span className="dot d3"/>采采購物 <b>21</b></div></div></article></section>{fresh.created&&<div className="recent-created">最新手動訂單：<b>{fresh.id}</b> · {fresh.customer} · NT$ {fresh.total.toLocaleString()} <span>{fresh.status}</span></div>}</>}

function Module({active,orders,show}:{active:string;orders:Order[];show:(v:string)=>void}){const rows=active==='訂單中心'?orders.map(o=>[o.id,`${o.brand} · ${o.source}`,o.customer,o.warehouse,o.status]):genericRows[active];return <section className="module"><div className="module-toolbar"><div><button className="selected">全部</button><button>待處理</button><button>進行中</button><button>已完成</button></div><div><input placeholder="搜尋編號、商品或 SKU"/><button onClick={()=>show('篩選條件已套用')}>篩選</button></div></div>{active==='採購管理'&&<div className="flowline">供應商　→　建立進貨單　→　待到貨　→　<strong>驗收入庫</strong>　→　庫存增加</div>}<div className="module-head"><span>編號 / SKU</span><span>品牌 / 人員 / 商品</span><span>內容</span><span>倉庫</span><span>狀態 / 數量</span></div>{rows.map(row=><button className="module-row" key={row[0]} onClick={()=>show(`正在查看：${row[0]}`)}>{row.map((cell,i)=><span key={i} className={i===0?'strong':i===4?'state':''}>{cell}</span>)}</button>)}</section>}
