'use client';
import Image from 'next/image';
import { FormEvent, PointerEvent, ReactNode, useEffect, useRef, useState } from 'react';

type View='home'|'history'|'profile';

type Material={id:string;name:string;category:string;unit:string;stock:number;cost:number;symbol:string;tone:string;image:string|null};
type Issue={id:string;date:string;items:{name:string;qty:number;unit:string}[];totalQty:number;status:string};
const seedMaterials:Material[]=[
 {id:'MAT-001',name:'T84 尺燈管',category:'照明燈具',unit:'支',stock:7,cost:185,symbol:'│',tone:'sun',image:'/materials/t8-light.jpg'},
 {id:'MAT-002',name:'16W 黃光燈泡',category:'照明燈具',unit:'個',stock:49,cost:95,symbol:'●',tone:'sun',image:'/materials/warm-led-bulb.jpg'},
 {id:'MAT-003',name:'LED 燈泡',category:'照明燈具',unit:'個',stock:2,cost:180,symbol:'●',tone:'sun',image:'/materials/led-bulb.png'},
 {id:'MAT-004',name:'景觀燈',category:'照明燈具',unit:'組',stock:1,cost:720,symbol:'⌂',tone:'sun',image:'/materials/path-light.png'},
 {id:'MAT-005',name:'投光燈',category:'照明燈具',unit:'組',stock:26,cost:1350,symbol:'◫',tone:'sun',image:'/materials/flood-light.jpg'},
 {id:'MAT-006',name:'短路帽',category:'五金配件',unit:'個',stock:50,cost:38,symbol:'⌒',tone:'mint',image:null},
 {id:'MAT-007',name:'無熔絲開關 30A2P',category:'開關設備',unit:'個',stock:22,cost:460,symbol:'▣',tone:'blue',image:'/materials/circuit-breaker.jpg'},
 {id:'MAT-008',name:'無熔絲開關 15A2P',category:'開關設備',unit:'個',stock:46,cost:390,symbol:'▣',tone:'blue',image:'/materials/circuit-breaker.jpg'},
 {id:'MAT-009',name:'120/150W Power',category:'電源設備',unit:'個',stock:191,cost:680,symbol:'ϟ',tone:'violet',image:'/materials/led-driver.jpg'},
 {id:'MAT-010',name:'7W Power',category:'電源設備',unit:'個',stock:23,cost:280,symbol:'ϟ',tone:'violet',image:'/materials/compact-led-driver.png'},
 {id:'MAT-011',name:'2.0 2C 電纜線',category:'電線電纜',unit:'米',stock:1362,cost:42,symbol:'◎',tone:'green',image:'/materials/multicore-cable.jpg'},
 {id:'MAT-012',name:'5.5 1C 電纜線',category:'電線電纜',unit:'米',stock:300,cost:76,symbol:'◎',tone:'green',image:'/materials/single-core-cable.jpg'},
];
const imageCredits=[['T8 燈管','https://commons.wikimedia.org/wiki/File:FluorescentT8razorback.jpg'],['黃光燈泡','https://commons.wikimedia.org/wiki/File:LED_light_bulb.jpg'],['LED 燈泡','https://commons.wikimedia.org/wiki/File:Led_light_bulb_-_led_lamp_1.png'],['景觀燈','https://commons.wikimedia.org/wiki/File:Pathlight_Landscape_Lighting.png'],['投光燈','https://commons.wikimedia.org/wiki/File:Led_flood_outdoor_lamp.JPG'],['無熔絲開關','https://commons.wikimedia.org/wiki/File:Circuit_breaker_2_pole_on_DIN_rail.JPG'],['LED 電源','https://commons.wikimedia.org/wiki/File:LED_Driver.jpg'],['小型 LED 電源','https://commons.wikimedia.org/wiki/File:LED-%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80.png'],['多芯電纜','https://commons.wikimedia.org/wiki/File:Copper_cable_5G16.JPG'],['單芯電纜','https://commons.wikimedia.org/wiki/File:Single-core-insulated-cable-for-electrical-power-transmission.jpg']];
const demoHistory:Issue[]=[
 {id:'OUT-0831-018',date:'今天・08:32',items:[{name:'LED 燈泡',qty:3,unit:'個'},{name:'無熔絲開關 30A2P',qty:1,unit:'個'}],totalQty:4,status:'已完成'},
 {id:'OUT-0830-024',date:'昨天・16:18',items:[{name:'2.0 2C 電纜線',qty:50,unit:'米'},{name:'短路帽',qty:8,unit:'個'}],totalQty:58,status:'已完成'},
 {id:'OUT-0829-011',date:'8 月 29 日・09:05',items:[{name:'投光燈',qty:2,unit:'組'}],totalQty:2,status:'已完成'},
];

export default function Home(){
 const[user,setUser]=useState<string|null>(null); const[loading,setLoading]=useState(true); const[entering,setEntering]=useState(false); const[authMode,setAuthMode]=useState<'login'|'register'>('login'); const[view,setView]=useState<View>('home'); const[category,setCategory]=useState('全部材料'); const[search,setSearch]=useState(''); const[cart,setCart]=useState<Record<string,number>>({}); const[cartOpen,setCartOpen]=useState(false); const[history,setHistory]=useState<Issue[]>(demoHistory); const[inventory,setInventory]=useState<Material[]>(seedMaterials); const[toast,setToast]=useState('');
 useEffect(()=>{const session=localStorage.getItem('junrong-user');if(session)setUser(session);try{const h=localStorage.getItem('junrong-issues');if(h)setHistory(JSON.parse(h));const saved=localStorage.getItem('junrong-tech-inventory');if(saved)setInventory(JSON.parse(saved))}catch{}const timer=setTimeout(()=>setLoading(false),1550);return()=>clearTimeout(timer)},[]);
 const categories=['全部材料','照明燈具','開關設備','電源設備','電線電纜','五金配件'];
 const visible=inventory.filter(m=>(category==='全部材料'||m.category===category)&&m.name.toLowerCase().includes(search.toLowerCase()));
 const cartItems=inventory.filter(m=>cart[m.id]>0); const cartKinds=cartItems.length; const cartTotal=Object.values(cart).reduce((s,n)=>s+n,0);
 const show=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2300)};
 const login=(name:string)=>{setEntering(true);setTimeout(()=>{setUser(name);localStorage.setItem('junrong-user',name);setView('home');setEntering(false);show(`歡迎回來，${name}師傅`)},1450)};
 const change=(m:Material,d:number)=>setCart(c=>({...c,[m.id]:Math.min(m.stock,Math.max(0,(c[m.id]||0)+d))}));
 const submit=()=>{if(!cartTotal)return;const issue:Issue={id:`OUT-${Date.now().toString().slice(-8)}`,date:'剛剛',items:cartItems.map(m=>({name:m.name,qty:cart[m.id],unit:m.unit})),totalQty:cartTotal,status:'已完成'};const next=[issue,...history];const nextInventory=inventory.map(m=>({...m,stock:Math.max(0,m.stock-(cart[m.id]||0))}));setHistory(next);setInventory(nextInventory);localStorage.setItem('junrong-issues',JSON.stringify(next));localStorage.setItem('junrong-tech-inventory',JSON.stringify(nextInventory));setCart({});setCartOpen(false);setView('history');show('領料完成，庫存已即時扣除')};
 if(loading||entering)return <div className={`splash-screen ${entering?'entering':''}`}><div className="splash-glow"/><Image className="splash-logo" src="/junrong-logo.png" alt="浚榮水電工程" width={360} height={360} priority/><div className="splash-loader"><span/></div><small>{entering?'登入成功・準備領料清單':'材料領用系統'}</small></div>;
 if(!user)return <Auth mode={authMode} setMode={setAuthMode} login={login}/>;
 return <div className="tech-app"><Topbar user={user}/><SwipeContent view={view} setView={setView}><div key={view} className="view-panel">{view==='home'?<HomeView user={user} materials={visible} categories={categories} category={category} setCategory={setCategory} search={search} setSearch={setSearch} cart={cart} change={change}/>:view==='history'?<HistoryView history={history}/>:<ProfileView user={user} logout={()=>{localStorage.removeItem('junrong-user');setUser(null)}}/>}</div></SwipeContent><BottomNav view={view} setView={setView}/>{cartTotal>0&&view==='home'&&<button className="floating-cart" onClick={()=>setCartOpen(true)}><span><b>{cartTotal}</b>本次領料</span><strong>查看清單</strong><i>→</i></button>}{cartOpen&&<CartSheet items={cartItems} cart={cart} change={change} close={()=>setCartOpen(false)} submit={submit} kinds={cartKinds} total={cartTotal}/>} {toast&&<div className="tech-toast">✓　{toast}</div>}</div>
}

function SwipeContent({view,setView,children}:{view:View;setView:(view:View)=>void;children:ReactNode}){
 const start=useRef<{x:number;y:number}|null>(null);const tabs:View[]=['home','history','profile'];
 const down=(e:PointerEvent<HTMLElement>)=>{if((e.target as HTMLElement).closest('button,input,a,label,select,textarea'))return;start.current={x:e.clientX,y:e.clientY}};
 const up=(e:PointerEvent<HTMLElement>)=>{if(!start.current)return;const dx=e.clientX-start.current.x;const dy=e.clientY-start.current.y;start.current=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.15)return;const active=tabs.indexOf(view);const next=Math.max(0,Math.min(tabs.length-1,active+(dx<0?1:-1)));if(next!==active)setView(tabs[next])};
 return <main className="tech-content swipe-content" onPointerDown={down} onPointerUp={up} onPointerCancel={()=>{start.current=null}}>{children}</main>
}

function Auth({mode,setMode,login}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;login:(n:string)=>void}){
 const[name,setName]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[showPass,setShowPass]=useState(false);const[agree,setAgree]=useState(false);const[error,setError]=useState('');
 const changeMode=(next:'login'|'register')=>{setMode(next);setError('')};
 const submit=(e:FormEvent)=>{e.preventDefault();setError('');const normalized=phone.replace(/\s/g,'');if(!/^09\d{8}$/.test(normalized)){setError('請輸入正確的 10 碼手機號碼');return}if(password.length<4){setError('密碼至少需要 4 個字元');return}const users:{name:string;phone:string;password:string}[]=JSON.parse(localStorage.getItem('junrong-users')||'[]');if(mode==='register'){if(!name.trim()){setError('請輸入師傅姓名');return}if(!agree){setError('請先確認資料正確');return}if(users.some(u=>u.phone===normalized)){setError('這個手機號碼已經註冊');return}localStorage.setItem('junrong-users',JSON.stringify([...users,{name:name.trim(),phone:normalized,password}]));login(name.trim())}else{const matched=users.find(u=>u.phone===normalized&&u.password===password);if(!matched){setError('手機號碼或密碼不正確');return}login(matched.name)}};
 return <div className="auth-page">
  <section className="auth-brand"><div className="auth-logo"><Image src="/junrong-logo.png" alt="浚榮水電工程" width={80} height={80}/><div><b>浚榮庫存</b><small>JUN RONG INVENTORY</small></div></div><div className="auth-message"><span>師傅領料系統</span><h1>拿料，不必再手寫。</h1><p>選擇材料、調整數量、確認送出。<br/>像點餐一樣簡單，幾秒完成領料。</p><div className="auth-points"><div><i>01</i><b>直接點選材料</b><small>不用再輸入完整材料名稱</small></div><div><i>02</i><b>立即完成出庫</b><small>送出後不需等待人工審核</small></div><div><i>03</i><b>紀錄隨時可查</b><small>每一筆領料清楚保存</small></div></div></div><div className="auth-decoration"><span/><span/><span/></div></section>
  <section className="auth-form-wrap"><form onSubmit={submit} className="auth-card"><div className="mobile-logo"><Image src="/junrong-logo.png" alt="浚榮水電工程" width={130} height={130}/></div><div className="auth-mode-tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>changeMode('login')}>登入</button><button type="button" className={mode==='register'?'active':''} onClick={()=>changeMode('register')}>註冊</button></div><small className="eyebrow">{mode==='login'?'WELCOME BACK':'NEW MEMBER'}</small><h2>{mode==='login'?'歡迎回來':'建立師傅帳號'}</h2><p>{mode==='login'?'登入後即可開始今天的領料作業。':'只需填寫一次，往後使用手機即可領料。'}</p>{mode==='register'&&<label>師傅姓名<input value={name} onChange={e=>setName(e.target.value)} placeholder="請輸入真實姓名" autoComplete="name"/></label>}<label>手機號碼<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel" placeholder="0912 345 678"/></label><label>登入密碼<div className="pass"><input value={password} onChange={e=>setPassword(e.target.value)} type={showPass?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="至少 4 個字元"/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?'隱藏':'顯示'}</button></div></label>{error&&<div className="auth-error"><span>!</span>{error}</div>}{mode==='register'&&<label className="agree"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>我已確認姓名與手機號碼正確</span></label>}<button className="auth-submit" type="submit"><span>{mode==='login'?'登入並開始領料':'完成註冊'}</span><b>→</b></button>{mode==='login'&&<><div className="auth-divider"><span>或</span></div><button className="demo-login" type="button" onClick={()=>login('王志明')}>使用示範帳號快速登入</button></>}</form><small className="auth-foot">浚榮水電工程・內部材料管理</small></section>
 </div>
}

function Topbar({user}:{user:string}){return <header className="tech-top"><div className="tech-logo"><Image src="/junrong-logo.png" alt="浚榮水電工程" width={44} height={44}/><div><b>浚榮庫存</b><small>師傅領料系統</small></div></div><button className="tech-avatar">{user.slice(0,1)}</button></header>}
function HomeView({user,materials,categories,category,setCategory,search,setSearch,cart,change}:{user:string;materials:Material[];categories:string[];category:string;setCategory:(s:string)=>void;search:string;setSearch:(s:string)=>void;cart:Record<string,number>;change:(m:Material,d:number)=>void}){return <><section className="welcome"><div><small>今天也辛苦了</small><h1>{user}師傅，<br/>今天要拿什麼料？</h1></div><div className="date-card"><b>31</b><span>8 月・週一</span></div></section><div className="smart-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜尋材料名稱或規格"/><button>掃碼</button></div><section className="quick-info"><div><span className="qi-icon">↗</span><p><small>本月已領料</small><b>18 筆</b></p></div><div><span className="qi-icon warm">★</span><p><small>我的常用材料</small><b>6 項</b></p></div><button>查看紀錄 →</button></section><section className="section-head"><div><h2>選擇材料</h2><p>點選需要的材料加入領料清單</p></div><span>{materials.length} 項</span></section><div className="category-scroll">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="order-grid">{materials.map(m=><article key={m.id} className={m.stock<=m.stock*.1?'low-stock':''}><div className={`item-visual ${m.tone}`}>{m.image?<Image className="material-photo" src={m.image} alt={`${m.name} 代表圖片`} fill sizes="(max-width: 600px) 45vw, 220px"/>:<span>{m.symbol}</span>}{m.stock<5&&<em>剩餘不多</em>}</div><small>{m.category}・{m.id}</small><h3>{m.name}</h3><p>庫存 <b>{m.stock.toLocaleString()}</b> {m.unit}</p>{cart[m.id]?<div className="order-counter"><button onClick={()=>change(m,-1)}>−</button><strong>{cart[m.id]}</strong><button onClick={()=>change(m,1)}>＋</button></div>:<button className="order-add" disabled={!m.stock} onClick={()=>change(m,1)}>＋ 加入清單</button>}</article>)}</div><details className="image-credits"><summary>材料圖片來源與授權</summary><p>圖片為同類材料示意，實際規格以材料名稱與庫存資料為準。</p><div>{imageCredits.map(([name,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{name}</a>)}</div></details></>}
function HistoryView({history}:{history:Issue[]}){return <section className="history-page"><div className="page-title"><small>MY RECORDS</small><h1>我的領料紀錄</h1><p>所有送出的領料都會保存在這裡。</p></div><div className="history-stats"><div><small>本月領料</small><b>{history.length} 筆</b></div><div><small>最近一次</small><b>{history[0]?.date||'—'}</b></div></div><div className="history-list">{history.map(h=><article key={h.id}><div className="history-icon">✓</div><div className="history-main"><small>{h.date}・{h.id}</small><b>{h.items.map(x=>x.name).join('、')}</b><p>{h.items.map(x=>`${x.name} ${x.qty} ${x.unit}`).join('・')}</p></div><div className="history-qty"><span>{h.status}</span><b>{h.totalQty}</b><small>總數量</small></div></article>)}</div></section>}
function ProfileView({user,logout}:{user:string;logout:()=>void}){return <section className="profile-page"><div className="profile-card"><div className="big-avatar">{user.slice(0,1)}</div><h1>{user}師傅</h1><p>浚榮工程・在職</p></div><div className="profile-menu"><button><span>個人資料</span><i>›</i></button><button><span>變更密碼</span><i>›</i></button><button><span>使用說明</span><i>›</i></button><button className="logout" onClick={logout}><span>登出帳號</span><i>›</i></button></div></section>}
function BottomNav({view,setView}:{view:View;setView:(v:View)=>void}){const tabs:View[]=['home','history','profile'];const labels=[['⌂','我要領料'],['≡','領料紀錄'],['●','我的帳號']];const active=Math.max(0,tabs.indexOf(view));const[drag,setDrag]=useState<number|null>(null);const position=(e:PointerEvent<HTMLElement>)=>{const r=e.currentTarget.getBoundingClientRect();return Math.max(0,Math.min(2,((e.clientX-r.left)/r.width)*3-.5))};const down=(e:PointerEvent<HTMLElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag(position(e))};const move=(e:PointerEvent<HTMLElement>)=>{if(drag!==null)setDrag(position(e))};const up=(e:PointerEvent<HTMLElement>)=>{if(drag===null)return;const i=Math.round(position(e));setView(tabs[i]);setDrag(null)};const pill=drag??active;return <nav className="bottom-nav" aria-label="主要導覽" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>setDrag(null)}><div className="nav-liquid" style={{transform:`translateX(calc(${pill*100}% + ${pill*14}px))`}}/>{tabs.map((tab,i)=><button key={tab} aria-current={view===tab?'page':undefined} className={view===tab?'active':''} onClick={()=>setView(tab)}><i>{labels[i][0]}</i><span>{labels[i][1]}</span></button>)}</nav>}
function CartSheet({items,cart,change,close,submit,kinds,total}:{items:Material[];cart:Record<string,number>;change:(m:Material,d:number)=>void;close:()=>void;submit:()=>void;kinds:number;total:number}){return <><button className="sheet-bg" onClick={close} aria-label="關閉清單"/><section className="cart-sheet"><div className="sheet-handle"/><div className="sheet-head"><div><small>領料確認</small><h2>本次領料清單</h2></div><button onClick={close}>×</button></div><div className="sheet-items">{items.map(m=><article key={m.id}><div className={`sheet-symbol ${m.tone}`}>{m.symbol}</div><div><b>{m.name}</b><small>庫存 {m.stock.toLocaleString()} {m.unit}</small></div><div className="sheet-counter"><button onClick={()=>change(m,-1)}>−</button><strong>{cart[m.id]}</strong><button onClick={()=>change(m,1)}>＋</button></div></article>)}</div><div className="sheet-summary"><span>共 {kinds} 種材料，總數量 {total}</span><small>確認後將立即完成出庫，不需等待審核。</small></div><button className="sheet-submit" onClick={submit}>確認領料並完成出庫 <span>→</span></button></section></>}
